### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by cboulanger** [hedii/zotero-api#5]
Hi, is this project still being used or or is it abandoned, given it was last updated four years ago?

Thanks for any information.

**Comment by hedii** [comment]
Hi. I made it few years ago for a single project that needed it. The zotero api has not changed since then so everything should be working fine. If you use it and see something wrong, you can open an issue or a pull request.

**Comment by cboulanger** [comment]
Thanks for your quick response and great to hear that you're still looking after the project.
